--- 
- name: 'install prometheus and alertmanager' 
  hosts: prometheus-server 
  connection: local
  become: true
  gather_facts: false 
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml  
    - prometheus: 
        job_name: Udapeople 
        scrape_interval: 5s
        filters:
          tag_name: Project 
          tag_value: Udapeople 
    - alerts: 
        email: 
          to: #email:change me
          from: #email:change me
          smarthost: smtp.gmail.com:587
          auth_password: #gmail api token:change me
    
  pre_tasks:
    - name: "wait 2 seconds for target connection to become reachable/usable."
      wait_for_connection: 
        timeout: 2
    - name: clean alertmanager
      shell: |
        sudo systemctl stop alertmanager.service
        sudo systemctl disable alertmanager.service
        sudo rm -rf /usr/local/bin/alertmanager*
        sudo rm -rf /var/lib/alertmanager*
        sudo rm -f /etc/systemd/system/alertmanager.service
        sudo systemctl daemon-reload
        sudo systemctl reset-failed
    - name: clean prometheus
      shell: |
        sudo systemctl stop prometheus.service
        sudo systemctl disable prometheus.service
        sudo rm -rf /usr/local/bin/prometheus*
        sudo rm -rf /etc/prometheus*
        sudo rm -rf /var/lib/prometheus*
        sudo rm -f /etc/systemd/system/prometheus.service
        sudo systemctl daemon-reload
        sudo systemctl reset-failed
  

  roles: 
    - prometheus 
    - alertmanager
    - enableservice 

