- name: enable alertmanager service 
  shell: |
    sudo systemctl daemon-reload 
    sudo systemctl enable alertmanager 
    sudo systemctl start alertmanager 

- name: enable prometheus service 
  shell: | 
    sudo systemctl daemon-reload 
    sudo systemctl start prometheus 
    sudo systemctl enable prometheus 
